export const TANSTACK_KEY = {
  PACKAGE_CATEGORY_ALL: "PACKAGE_CATEGORY_ALL",
  PACKAGE_CATEGORY_ONE: "PACKAGE_CATEGORY_ONE",

  PACKAGE_ALL: "PACKAGE_ALL",
  PACKAGE_ONE: "PACKAGE_ONE",

  PACKAGE_FEATURE_ALL: "PACKAGE_FEATURE_ALL",
  PACKAGE_FEATURE_ONE: "PACKAGE_FEATURE_ONE",

  SUBSCRIPTION_DURATION_ALL: "SUBSCRIPTION_DURATION_ALL",
  SUBSCRIPTION_DURATION_ONE: "SUBSCRIPTION_DURATION_ONE",

  CART_ITEM_ALL: "CART_ITEM_ALL",
  CART_ITEM_ONE: "CART_ITEM_ONE",

  GUEST_ORDER_ALL: "GUEST_ORDER_ALL",
  GUEST_ORDER_ONE: "GUEST_ORDER_ONE",

  ME: "ME",

  GUEST_ORDERS_ME: "GUEST_ORDERS_ME",

  SUBSCRIPTION_ALL: "SUBSCRIPTION_ALL",

  NOTIFICATION_ALL: "NOTIFICATION_ALL",
};
